plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/Users/eliaschouchani/Desktop/ch-business-services-site"
publishOrigin = "default"
base = "/Users/eliaschouchani/Desktop/ch-business-services-site"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]